### ISSUE TITLE
Using react compiler eslint rules causes error

### ISSUE THREAD

**Issue by omridevk** [gregberge/react-merge-refs#34]
## To Reproduce

Create a repo with eslint compiler rules https://react.dev/learn/react-compiler

``` Ref values (the `current` property) may not be accessed during render. ```
## Expected behavior

No eslint errors should appear

## Link to repl or repo (highly encouraged)

Please provide a minimal repository on GitHub.

Issues without a reproduction link are likely to stall.

## Run `npx envinfo --system --binaries --npmPackages react-merge-refs,react,react-dom --markdown --clipboard`

Paste the results here:

```bash
## System:
 - OS: macOS 15.1
 - CPU: (10) arm64 Apple M1 Pro
 - Memory: 70.02 MB / 32.00 GB
 - Shell: 3.7.1 - /opt/homebrew/bin/fish
## Binaries:
 - Node: 22.5.1 - ~/.nvm/versions/node/v22.5.1/bin/node
 - Yarn: 1.22.22 - ~/.nvm/versions/node/v22.5.1/bin/yarn
 - npm: 10.8.2 - ~/.nvm/versions/node/v22.5.1/bin/npm
 - pnpm: 8.15.4 - ~/Library/pnpm/pnpm
## npmPackages:
 - react: ^18.3.1 => 18.3.1
 - react-dom: ^18.3.1 => 18.3.1

```

**Comment by gregberge** [comment]
The current implementation is OK, you may want to wrap it in a `useMemo`:

```ts
const ref = React.useMemo(() => mergeRefs([refA, refB]), [refA, refB])
```
